[
    {
       "source":"NINJABLD_S001_S001_T001.MOV",
       "start":"00:03:59",
       "end":"00:18:21",
       "name":"2020-10-04 Прославление"
    },
    {
        "source":"NINJABLD_S001_S001_T001.MOV",
        "start":"00:30:07",
        "end":"01:08:00",
        "name":"2020-10-04 Проповедь"
     },
    {
        "source":"NINJABLD_S001_S001_T002.MOV",
        "start":"01:12:25",
        "end":"01:17:16",
        "name":"2020-10-04 Прославление 2"
     }
 ]

